USE gift_tree;
CREATE TABLE TREE (
TREE_ID INT NOT NULL AUTO_INCREMENT,
TREE_NAME TEXT NOT NULL,
TREE_SPECIES TEXT NOT NULL,
COUNTRY TEXT NOT NULL,
GROWTH_RATE INT NOT NULL,
PRICE INT NOT NULL,
CO2_EMISSIONS INT NOT NULL,
LAND_AREA INT NOT NULL,
TREE_DATE DATE NOT NULL,
TREE_DESCRIPTION TEXT NOT NULL,
PRIMARY KEY (TREE_ID)
);